title: セキュリティ／プライバシー・リテラシー（仮）
description: 新人が最低限回避すべき事故（秘密情報/権限/データ分類/誤公開等）と、チェックリスト運用を扱う。
author: 株式会社アイティードゥ
lang: ja
url: https://itdojp.github.io
baseurl: /security-privacy-literacy-book
repository: https://github.com/itdojp/security-privacy-literacy-book
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-relative-links
- jekyll-optional-front-matter
defaults:
- scope:
    path: ''
  values:
    layout: book
permalink: pretty
license_text: CC BY-NC-SA 4.0
